//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class Logger : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Logger(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Logger obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Logger obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Logger() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

    public static void Log(Logger.LogLevel level, [global::System.Diagnostics.CodeAnalysis.StringSyntax(global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute.CompositeFormat)] string format, params object[] args)
    {
        LogString(level, String.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
    }

    public static void LogTempDebug(string message, [global::System.Runtime.CompilerServices.CallerFilePath] string file = "", [global::System.Runtime.CompilerServices.CallerLineNumber] int line = 0)
    {
        LogTempDebugString(message, file, line);
    }

    public static void LogDebug([global::System.Diagnostics.CodeAnalysis.StringSyntax(global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute.CompositeFormat)] string format, params object[] args)
    {
        LogDebugString(String.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
    }

    public static void LogInfo([global::System.Diagnostics.CodeAnalysis.StringSyntax(global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute.CompositeFormat)] string format, params object[] args)
    {
        LogInfoString(String.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
    }

    public static void LogWarning([global::System.Diagnostics.CodeAnalysis.StringSyntax(global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute.CompositeFormat)] string format, params object[] args)
    {
        LogWarningString(String.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
    }

    public static void LogError([global::System.Diagnostics.CodeAnalysis.StringSyntax(global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute.CompositeFormat)] string format, params object[] args)
    {
        LogErrorString(String.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
    }

    public static void LogFatal([global::System.Diagnostics.CodeAnalysis.StringSyntax(global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute.CompositeFormat)] string format, params object[] args)
    {
        LogFatalString(String.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
    }

  public static Logger.LogLevel minimumConsoleLevel {
    set {
      CorePINVOKE.Logger_minimumConsoleLevel_set((int)value);
    } 
    get {
      Logger.LogLevel ret = (Logger.LogLevel)CorePINVOKE.Logger_minimumConsoleLevel_get();
      return ret;
    } 
  }

  public static Logger.LogLevel minimumFileLevel {
    set {
      CorePINVOKE.Logger_minimumFileLevel_set((int)value);
    } 
    get {
      Logger.LogLevel ret = (Logger.LogLevel)CorePINVOKE.Logger_minimumFileLevel_get();
      return ret;
    } 
  }

  public static void OpenFile(SWIGTYPE_p_std__filesystem__path filepath) {
    CorePINVOKE.Logger_OpenFile(SWIGTYPE_p_std__filesystem__path.getCPtr(filepath));
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  public static void OpenDefaultFile() {
    CorePINVOKE.Logger_OpenDefaultFile();
  }

  public static bool HasFileOpen() {
    bool ret = CorePINVOKE.Logger_HasFileOpen();
    return ret;
  }

  public static void CloseFile() {
    CorePINVOKE.Logger_CloseFile();
  }

  public static void Synchronize() {
    CorePINVOKE.Logger_Synchronize();
  }

  private static void LogString(Logger.LogLevel level, string format) {
    CorePINVOKE.Logger_LogString((int)level, format);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  private static void LogTempDebugString(string format, string file, int line) {
    CorePINVOKE.Logger_LogTempDebugString(format, file, line);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  private static void LogDebugString(string format) {
    CorePINVOKE.Logger_LogDebugString(format);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  private static void LogInfoString(string format) {
    CorePINVOKE.Logger_LogInfoString(format);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  private static void LogWarningString(string format) {
    CorePINVOKE.Logger_LogWarningString(format);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  private static void LogErrorString(string format) {
    CorePINVOKE.Logger_LogErrorString(format);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  private static void LogFatalString(string format) {
    CorePINVOKE.Logger_LogFatalString(format);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  public enum LogLevel {
    TemporaryDebug,
    Debug,
    Info,
    Warning,
    Error,
    Fatal
  }

}

}
