//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public enum MemoryBarrier {
  VertexAttribArrayBarrierBit,
  ElementArrayBarrierBit,
  UniformBarrierBit,
  TextureFetchBarrierBit,
  ShaderImageAccessBarrierBit,
  CommandBarrierBit,
  PixelBufferBarrierBit,
  TextureUpdateBarrierBit,
  BufferUpdateBarrierBit,
  ClientMappedBufferBarrierBit,
  FramebufferBarrierBit,
  TransformFeedbackBarrierBit,
  AtomicCounterBarrierBit,
  ShaderStorageBarrierBit,
  QueryBufferBarrierBit,
  AllBarrierBits
}

}
