//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class RenderPassBeginInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RenderPassBeginInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RenderPassBeginInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(RenderPassBeginInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~RenderPassBeginInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CorePINVOKE.delete_RenderPassBeginInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_XnorCore__FrameBuffer frameBuffer {
    set {
      CorePINVOKE.RenderPassBeginInfo_frameBuffer_set(swigCPtr, SWIGTYPE_p_XnorCore__FrameBuffer.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CorePINVOKE.RenderPassBeginInfo_frameBuffer_get(swigCPtr);
      SWIGTYPE_p_XnorCore__FrameBuffer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_XnorCore__FrameBuffer(cPtr, false);
      return ret;
    } 
  }

  public Vector2i renderAreaOffset {
    set {
      CorePINVOKE.RenderPassBeginInfo_renderAreaOffset_set(swigCPtr, Vector2i.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CorePINVOKE.RenderPassBeginInfo_renderAreaOffset_get(swigCPtr);
      Vector2i ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector2i(cPtr, false);
      return ret;
    } 
  }

  public Vector2i renderAreaExtent {
    set {
      CorePINVOKE.RenderPassBeginInfo_renderAreaExtent_set(swigCPtr, Vector2i.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CorePINVOKE.RenderPassBeginInfo_renderAreaExtent_get(swigCPtr);
      Vector2i ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector2i(cPtr, false);
      return ret;
    } 
  }

  public BufferFlag clearBufferFlags {
    set {
      CorePINVOKE.RenderPassBeginInfo_clearBufferFlags_set(swigCPtr, (int)value);
    } 
    get {
      BufferFlag ret = (BufferFlag)CorePINVOKE.RenderPassBeginInfo_clearBufferFlags_get(swigCPtr);
      return ret;
    } 
  }

  public Vector4 clearColor {
    set {
      CorePINVOKE.RenderPassBeginInfo_clearColor_set(swigCPtr, Vector4.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CorePINVOKE.RenderPassBeginInfo_clearColor_get(swigCPtr);
      Vector4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector4(cPtr, false);
      return ret;
    } 
  }

  public RenderPassBeginInfo() : this(CorePINVOKE.new_RenderPassBeginInfo(), true) {
  }

}

}
