//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class AudioTrack : Resource {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal AudioTrack(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CoreCNative.AudioTrack_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AudioTrack obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AudioTrack obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_AudioTrack(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public static SWIGTYPE_p_std__arrayT_char_const_p_4_t FileExtensions {
    get {
      global::System.IntPtr cPtr = CoreCNative.AudioTrack_FileExtensions_get();
      SWIGTYPE_p_std__arrayT_char_const_p_4_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__arrayT_char_const_p_4_t(cPtr, false);
      return ret;
    } 
  }

  public AudioTrack() : this(CoreCNative.new_AudioTrack__SWIG_0(), true) {
  }

  public AudioTrack(string name) : this(CoreCNative.new_AudioTrack__SWIG_1(name), true) {
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
  }

  public override bool Load(SWIGTYPE_p_XnorCore__PointerT_XnorCore__File_t file) {
    bool ret = CoreCNative.AudioTrack_Load__SWIG_0(swigCPtr, SWIGTYPE_p_XnorCore__PointerT_XnorCore__File_t.getCPtr(file));
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool Load(SWIGTYPE_p_unsigned_char buffer, long length) {
    bool ret = CoreCNative.AudioTrack_Load__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(buffer), length);
    return ret;
  }

  public override void CreateInInterface() {
    CoreCNative.AudioTrack_CreateInInterface(swigCPtr);
  }

  public override void DestroyInInterface() {
    CoreCNative.AudioTrack_DestroyInInterface(swigCPtr);
  }

  public override void Unload() {
    CoreCNative.AudioTrack_Unload(swigCPtr);
  }

  public int GetDataSize() {
    int ret = CoreCNative.AudioTrack_GetDataSize(swigCPtr);
    return ret;
  }

  public ushort GetChannels() {
    ushort ret = CoreCNative.AudioTrack_GetChannels(swigCPtr);
    return ret;
  }

  public int GetSampleRate() {
    int ret = CoreCNative.AudioTrack_GetSampleRate(swigCPtr);
    return ret;
  }

  public ushort GetBitDepth() {
    ushort ret = CoreCNative.AudioTrack_GetBitDepth(swigCPtr);
    return ret;
  }

  public AudioBuffer GetBuffer() {
    global::System.IntPtr cPtr = CoreCNative.AudioTrack_GetBuffer(swigCPtr);
    AudioBuffer ret = (cPtr == global::System.IntPtr.Zero) ? null : new AudioBuffer(cPtr, false);
    return ret;
  }

}

}
