//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class AudioBuffer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AudioBuffer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AudioBuffer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AudioBuffer obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AudioBuffer() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_AudioBuffer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public AudioBuffer() : this(CoreCNative.new_AudioBuffer__SWIG_0(), true) {
  }

  public AudioBuffer(int size) : this(CoreCNative.new_AudioBuffer__SWIG_1(size), true) {
  }

  public AudioBuffer(AudioTrack track) : this(CoreCNative.new_AudioBuffer__SWIG_2(AudioTrack.getCPtr(track)), true) {
  }

  public void SetData(AudioTrack track) {
    CoreCNative.AudioBuffer_SetData__SWIG_0(swigCPtr, AudioTrack.getCPtr(track));
  }

  public void SetData(SWIGTYPE_p_void data, int length, ushort channels, ushort bitDepth, int sampleRate) {
    CoreCNative.AudioBuffer_SetData__SWIG_1(swigCPtr, SWIGTYPE_p_void.getCPtr(data), length, channels, bitDepth, sampleRate);
  }

  public uint GetHandle() {
    uint ret = CoreCNative.AudioBuffer_GetHandle(swigCPtr);
    return ret;
  }

}

}
