//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class AudioListener : Component {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal AudioListener(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CoreCNative.AudioListener_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AudioListener obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AudioListener obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_AudioListener(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public bool dopplerEffect {
    set {
      CoreCNative.AudioListener_dopplerEffect_set(swigCPtr, value);
    } 
    get {
      bool ret = CoreCNative.AudioListener_dopplerEffect_get(swigCPtr);
      return ret;
    } 
  }

  public AudioListener() : this(CoreCNative.new_AudioListener(), true) {
  }

  protected override void Update() {
    CoreCNative.AudioListener_Update(swigCPtr);
  }

  public float GetVolume() {
    float ret = CoreCNative.AudioListener_GetVolume(swigCPtr);
    return ret;
  }

  public void SetVolume(float newVolume) {
    CoreCNative.AudioListener_SetVolume(swigCPtr, newVolume);
  }

}

}
