//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class BoxCollider : Collider {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal BoxCollider(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CoreCNative.BoxCollider_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BoxCollider obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(BoxCollider obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_BoxCollider(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public BoxCollider() : this(CoreCNative.new_BoxCollider(), true) {
  }

  protected override void Begin() {
    CoreCNative.BoxCollider_Begin(swigCPtr);
  }

  protected override void Update() {
    CoreCNative.BoxCollider_Update(swigCPtr);
  }

  public Vector3 center {
    set {
      CoreCNative.BoxCollider_center_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.BoxCollider_center_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

  public Vector3 size {
    set {
      CoreCNative.BoxCollider_size_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.BoxCollider_size_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

}

}
