//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class CollisionExitEvent : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CollisionExitEvent(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CollisionExitEvent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CollisionExitEvent obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CollisionExitEvent() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_CollisionExitEvent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public void Invoke(Collider args1, Collider args2) {
    CoreCNative.CollisionExitEvent_Invoke(swigCPtr, Collider.getCPtr(args1), Collider.getCPtr(args2));
  }

  public void Clear() {
    CoreCNative.CollisionExitEvent_Clear(swigCPtr);
  }

  public CollisionExitEvent OperatorAddAssign(SWIGTYPE_p_std__functionT_void_t func) {
    CollisionExitEvent ret = new CollisionExitEvent(CoreCNative.CollisionExitEvent_OperatorAddAssign(swigCPtr, SWIGTYPE_p_std__functionT_void_t.getCPtr(func)), false);
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollisionExitEvent OperatorSubAssign(SWIGTYPE_p_std__functionT_void_t func) {
    CollisionExitEvent ret = new CollisionExitEvent(CoreCNative.CollisionExitEvent_OperatorSubAssign(swigCPtr, SWIGTYPE_p_std__functionT_void_t.getCPtr(func)), false);
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
    return ret;
  }

  public CollisionExitEvent() : this(CoreCNative.new_CollisionExitEvent(), true) {
  }

}

}
