//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class ComponentList : 
    global::System.Collections.Generic.IEnumerable<global::Xnor.Core.Component>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ComponentList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ComponentList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ComponentList obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ComponentList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_ComponentList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

    private class ListEnumerator : global::System.Collections.Generic.IEnumerator<Component>
    {
        private readonly ComponentList list;
        private uint index;
        private Component current;
        
        public ListEnumerator(ComponentList list)
        {
            this.list = list;
            Reset();
        }
        
        public bool MoveNext()
        {
            if (index >= list.GetSize())
            {
                current = null;
                return false;
            }

            current = list[index++];

            return true;
        }

        public void Reset()
        {
            index = 0;
            current = null;
        }

        public Component Current { get => current; }

        object global::System.Collections.IEnumerator.Current => Current;

        public void Dispose() { }
    }

    public global::System.Collections.Generic.IEnumerator<Component> GetEnumerator()
    {
        return new ListEnumerator(this);
    }

    global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public Component this[uint index]
    {
        get => CoreC.ComponentListGetItem(this, index);
    }

  public ComponentList() : this(CoreCNative.new_ComponentList__SWIG_0(), true) {
  }

  public ComponentList(uint size) : this(CoreCNative.new_ComponentList__SWIG_1(size), true) {
  }

  public ComponentList(uint size, Component defaultValue) : this(CoreCNative.new_ComponentList__SWIG_2(size, Component.getCPtr(defaultValue)), true) {
  }

  public ComponentList(SWIGTYPE_p_std__initializer_listT_XnorCore__Component_p_t values) : this(CoreCNative.new_ComponentList__SWIG_3(SWIGTYPE_p_std__initializer_listT_XnorCore__Component_p_t.getCPtr(values)), true) {
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
  }

  public void Resize(uint size) {
    CoreCNative.ComponentList_Resize(swigCPtr, size);
  }

  public void Clear() {
    CoreCNative.ComponentList_Clear(swigCPtr);
  }

  public void Add() {
    CoreCNative.ComponentList_Add__SWIG_0(swigCPtr);
  }

  public void Add(Component element) {
    CoreCNative.ComponentList_Add__SWIG_1(swigCPtr, Component.getCPtr(element));
  }

  public void AddRange(SWIGTYPE_p_p_XnorCore__Component data, uint count) {
    CoreCNative.ComponentList_AddRange__SWIG_0(swigCPtr, SWIGTYPE_p_p_XnorCore__Component.getCPtr(data), count);
  }

  public void AddRange(SWIGTYPE_p_std__initializer_listT_XnorCore__Component_p_t values) {
    CoreCNative.ComponentList_AddRange__SWIG_1(swigCPtr, SWIGTYPE_p_std__initializer_listT_XnorCore__Component_p_t.getCPtr(values));
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
  }

  public void Fill(Component value) {
    CoreCNative.ComponentList_Fill(swigCPtr, Component.getCPtr(value));
  }

  public void Insert(uint index) {
    CoreCNative.ComponentList_Insert__SWIG_0(swigCPtr, index);
  }

  public void Insert(Component element, uint index) {
    CoreCNative.ComponentList_Insert__SWIG_1(swigCPtr, Component.getCPtr(element), index);
  }

  public void Remove(Component element) {
    CoreCNative.ComponentList_Remove(swigCPtr, Component.getCPtr(element));
  }

  public void RemoveAt(uint index) {
    CoreCNative.ComponentList_RemoveAt(swigCPtr, index);
  }

  public void RemoveRange(uint start, uint end) {
    CoreCNative.ComponentList_RemoveRange(swigCPtr, start, end);
  }

  public bool Contains(Component element) {
    bool ret = CoreCNative.ComponentList_Contains(swigCPtr, Component.getCPtr(element));
    return ret;
  }

  public void Iterate(SWIGTYPE_p_std__functionT_void_fXnorCore__Component_ppF_t lambda) {
    CoreCNative.ComponentList_Iterate__SWIG_0(swigCPtr, SWIGTYPE_p_std__functionT_void_fXnorCore__Component_ppF_t.getCPtr(lambda));
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
  }

  public void Iterate(SWIGTYPE_p_std__functionT_void_fXnorCore__Component_pconst_pF_t lambda) {
    CoreCNative.ComponentList_Iterate__SWIG_1(swigCPtr, SWIGTYPE_p_std__functionT_void_fXnorCore__Component_pconst_pF_t.getCPtr(lambda));
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
  }

  public bool Exists(SWIGTYPE_p_std__functionT_bool_fXnorCore__Component_pconst_pF_t lambda) {
    bool ret = CoreCNative.ComponentList_Exists(swigCPtr, SWIGTYPE_p_std__functionT_bool_fXnorCore__Component_pconst_pF_t.getCPtr(lambda));
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_p_XnorCore__Component Find(SWIGTYPE_p_std__functionT_bool_fXnorCore__Component_pconst_pF_t lambda) {
    global::System.IntPtr cPtr = CoreCNative.ComponentList_Find(swigCPtr, SWIGTYPE_p_std__functionT_bool_fXnorCore__Component_pconst_pF_t.getCPtr(lambda));
    SWIGTYPE_p_p_XnorCore__Component ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_XnorCore__Component(cPtr, false);
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint GetSize() {
    uint ret = CoreCNative.ComponentList_GetSize(swigCPtr);
    return ret;
  }

  public uint GetCapacity() {
    uint ret = CoreCNative.ComponentList_GetCapacity(swigCPtr);
    return ret;
  }

}

}
