//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class DirectionalLightData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DirectionalLightData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DirectionalLightData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DirectionalLightData obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~DirectionalLightData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_DirectionalLightData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Vector3 color {
    set {
      CoreCNative.DirectionalLightData_color_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.DirectionalLightData_color_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

  public float intensity {
    set {
      CoreCNative.DirectionalLightData_intensity_set(swigCPtr, value);
    } 
    get {
      float ret = CoreCNative.DirectionalLightData_intensity_get(swigCPtr);
      return ret;
    } 
  }

  public Vector3 direction {
    set {
      CoreCNative.DirectionalLightData_direction_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.DirectionalLightData_direction_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

  public int isDirlightCastingShadow {
    set {
      CoreCNative.DirectionalLightData_isDirlightCastingShadow_set(swigCPtr, value);
    } 
    get {
      int ret = CoreCNative.DirectionalLightData_isDirlightCastingShadow_get(swigCPtr);
      return ret;
    } 
  }

  public int cascadeCount {
    set {
      CoreCNative.DirectionalLightData_cascadeCount_set(swigCPtr, value);
    } 
    get {
      int ret = CoreCNative.DirectionalLightData_cascadeCount_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_float cascadePlaneDistance {
    set {
      CoreCNative.DirectionalLightData_cascadePlaneDistance_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.DirectionalLightData_cascadePlaneDistance_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public DirectionalLightData() : this(CoreCNative.new_DirectionalLightData(), true) {
  }

}

}
