//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class DirectionalLight : Light {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DirectionalLight(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CoreCNative.DirectionalLight_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DirectionalLight obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(DirectionalLight obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_DirectionalLight(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Vector2 leftRight {
    set {
      CoreCNative.DirectionalLight_leftRight_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.DirectionalLight_leftRight_get(swigCPtr);
			Vector2 ret = (Vector2) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector2));
			return ret;
		}
	
  }

  public Vector2 bottomTop {
    set {
      CoreCNative.DirectionalLight_bottomTop_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.DirectionalLight_bottomTop_get(swigCPtr);
			Vector2 ret = (Vector2) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector2));
			return ret;
		}
	
  }

  public DirectionalLight() : this(CoreCNative.new_DirectionalLight(), true) {
  }

  public  Vector3  GetLightDirection() {
			Vector3 ret = CoreCNative.DirectionalLight_GetLightDirection(swigCPtr);
			return ret;
		}

}

}
