//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class GamepadInput : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GamepadInput(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GamepadInput obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(GamepadInput obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~GamepadInput() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_GamepadInput(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool isConnected {
    set {
      CoreCNative.GamepadInput_isConnected_set(swigCPtr, value);
    } 
    get {
      bool ret = CoreCNative.GamepadInput_isConnected_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__arrayT_float_static_castT_unsigned_int_t_fXnorCore__GamepadAxis__CountF_t axisValues {
    set {
      CoreCNative.GamepadInput_axisValues_set(swigCPtr, SWIGTYPE_p_std__arrayT_float_static_castT_unsigned_int_t_fXnorCore__GamepadAxis__CountF_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.GamepadInput_axisValues_get(swigCPtr);
      SWIGTYPE_p_std__arrayT_float_static_castT_unsigned_int_t_fXnorCore__GamepadAxis__CountF_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__arrayT_float_static_castT_unsigned_int_t_fXnorCore__GamepadAxis__CountF_t(cPtr, false);
      return ret;
    } 
  }

  public GamepadInput() : this(CoreCNative.new_GamepadInput(), true) {
  }

  public static readonly float NullAnalogValue = CoreCNative.GamepadInput_NullAnalogValue_get();
}

}
