//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public enum GpuMemoryBarrier {
  VertexAttribArrayBarrierBit = 1 << 0,
  ElementArrayBarrierBit = 1 << 1,
  UniformBarrierBit = 1 << 2,
  TextureFetchBarrierBit = 1 << 3,
  ShaderImageAccessBarrierBit = 1 << 4,
  CommandBarrierBit = 1 << 5,
  PixelBufferBarrierBit = 1 << 6,
  TextureUpdateBarrierBit = 1 << 7,
  BufferUpdateBarrierBit = 1 << 8,
  ClientMappedBufferBarrierBit = 1 << 9,
  FramebufferBarrierBit = 1 << 10,
  TransformFeedbackBarrierBit = 1 << 11,
  AtomicCounterBarrierBit = 1 << 12,
  ShaderStorageBarrierBit = 1 << 13,
  QueryBufferBarrierBit = 1 << 14,
  AllBarrierBits = 1 << 15
}

}
