//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public static class Input {
  public static bool mouseLocked {
    set {
      CoreCNative.Input_mouseLocked_set(value);
    } 
    get {
      bool ret = CoreCNative.Input_mouseLocked_get();
      return ret;
    } 
  }

  public static bool GetKey(Key key, KeyStatus status) {
    bool ret = CoreCNative.Input_GetKey__SWIG_0((int)key, (int)status);
    return ret;
  }

  public static bool GetKey(Key key) {
    bool ret = CoreCNative.Input_GetKey__SWIG_1((int)key);
    return ret;
  }

  public static bool GetMouseButton(MouseButton mouseButton, MouseButtonStatus status) {
    bool ret = CoreCNative.Input_GetMouseButton__SWIG_0((int)mouseButton, (int)status);
    return ret;
  }

  public static bool GetMouseButton(MouseButton mouseButton) {
    bool ret = CoreCNative.Input_GetMouseButton__SWIG_1((int)mouseButton);
    return ret;
  }

  public static bool GetGamepadButton(uint gamePadId, GamepadButton gamepadButton, GamepadButtonStatus buttonStatus) {
    bool ret = CoreCNative.Input_GetGamepadButton__SWIG_0(gamePadId, (int)gamepadButton, (int)buttonStatus);
    return ret;
  }

  public static bool GetGamepadButton(uint gamePadId, GamepadButton gamepadButton) {
    bool ret = CoreCNative.Input_GetGamepadButton__SWIG_1(gamePadId, (int)gamepadButton);
    return ret;
  }

}

}
