//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class Light : Component {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Light(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CoreCNative.Light_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Light obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Light obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_Light(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Colorf color {
    set {
      CoreCNative.Light_color_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.Light_color_get(swigCPtr);
			Colorf ret = (Colorf) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Colorf));
			return ret;
		}
	
  }

  public float intensity {
    set {
      CoreCNative.Light_intensity_set(swigCPtr, value);
    } 
    get {
      float ret = CoreCNative.Light_intensity_get(swigCPtr);
      return ret;
    } 
  }

  public bool castShadow {
    set {
      CoreCNative.Light_castShadow_set(swigCPtr, value);
    } 
    get {
      bool ret = CoreCNative.Light_castShadow_get(swigCPtr);
      return ret;
    } 
  }

  public float near {
    set {
      CoreCNative.Light_near_set(swigCPtr, value);
    } 
    get {
      float ret = CoreCNative.Light_near_get(swigCPtr);
      return ret;
    } 
  }

  public float far {
    set {
      CoreCNative.Light_far_set(swigCPtr, value);
    } 
    get {
      float ret = CoreCNative.Light_far_get(swigCPtr);
      return ret;
    } 
  }

  public Light() : this(CoreCNative.new_Light(), true) {
  }

}

}
