//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class Mesh : Resource {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Mesh(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CoreCNative.Mesh_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Mesh obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Mesh obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_Mesh(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public static SWIGTYPE_p_std__arrayT_char_const_p_5_t FileExtensions {
    get {
      global::System.IntPtr cPtr = CoreCNative.Mesh_FileExtensions_get();
      SWIGTYPE_p_std__arrayT_char_const_p_5_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_std__arrayT_char_const_p_5_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_XnorCore__ListT_XnorCore__PointerT_XnorCore__Model_t_t models {
    set {
      CoreCNative.Mesh_models_set(swigCPtr, SWIGTYPE_p_XnorCore__ListT_XnorCore__PointerT_XnorCore__Model_t_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.Mesh_models_get(swigCPtr);
      SWIGTYPE_p_XnorCore__ListT_XnorCore__PointerT_XnorCore__Model_t_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_XnorCore__ListT_XnorCore__PointerT_XnorCore__Model_t_t(cPtr, false);
      return ret;
    } 
  }

  public Mesh() : this(CoreCNative.new_Mesh__SWIG_0(), true) {
  }

  public Mesh(string name) : this(CoreCNative.new_Mesh__SWIG_1(name), true) {
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
  }

  public override bool Load(SWIGTYPE_p_XnorCore__PointerT_XnorCore__File_t file) {
    bool ret = CoreCNative.Mesh_Load__SWIG_0(swigCPtr, SWIGTYPE_p_XnorCore__PointerT_XnorCore__File_t.getCPtr(file));
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
    return ret;
  }

  public override bool Load(SWIGTYPE_p_unsigned_char buffer, long length) {
    bool ret = CoreCNative.Mesh_Load__SWIG_1(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(buffer), length);
    return ret;
  }

  public override void CreateInInterface() {
    CoreCNative.Mesh_CreateInInterface(swigCPtr);
  }

  public SWIGTYPE_p_XnorCore__PointerT_XnorCore__Animation_t GetAnimation(uint id) {
    SWIGTYPE_p_XnorCore__PointerT_XnorCore__Animation_t ret = new SWIGTYPE_p_XnorCore__PointerT_XnorCore__Animation_t(CoreCNative.Mesh_GetAnimation(swigCPtr, id), true);
    return ret;
  }

}

}
