//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public enum MessageBoxFlags {
  None,
  IconWarning,
  IconError,
  IconInformation,
  DefaultButton1,
  DefaultButton2,
  DefaultButton3,
  DefaultButton4
}

}
