//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class SkinnedMeshRenderer : Component {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal SkinnedMeshRenderer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CoreCNative.SkinnedMeshRenderer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SkinnedMeshRenderer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SkinnedMeshRenderer obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_SkinnedMeshRenderer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SkinnedMeshRenderer() : this(CoreCNative.new_SkinnedMeshRenderer(), true) {
  }

  protected override void Begin() {
    CoreCNative.SkinnedMeshRenderer_Begin(swigCPtr);
  }

  public override void OnRendering() {
    CoreCNative.SkinnedMeshRenderer_OnRendering(swigCPtr);
  }

  public SWIGTYPE_p_XnorCore__PointerT_XnorCore__Mesh_t mesh {
    set {
      CoreCNative.SkinnedMeshRenderer_mesh_set(swigCPtr, SWIGTYPE_p_XnorCore__PointerT_XnorCore__Mesh_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.SkinnedMeshRenderer_mesh_get(swigCPtr);
      SWIGTYPE_p_XnorCore__PointerT_XnorCore__Mesh_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_XnorCore__PointerT_XnorCore__Mesh_t(cPtr, false);
      return ret;
    } 
  }

  public Material material {
    set {
      CoreCNative.SkinnedMeshRenderer_material_set(swigCPtr, Material.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.SkinnedMeshRenderer_material_get(swigCPtr);
      Material ret = (cPtr == global::System.IntPtr.Zero) ? null : new Material(cPtr, false);
      return ret;
    } 
  }

  public bool drawModelAabb {
    set {
      CoreCNative.SkinnedMeshRenderer_drawModelAabb_set(swigCPtr, value);
    } 
    get {
      bool ret = CoreCNative.SkinnedMeshRenderer_drawModelAabb_get(swigCPtr);
      return ret;
    } 
  }

  public void StartAnimation(SWIGTYPE_p_XnorCore__PointerT_XnorCore__Animation_t animation) {
    CoreCNative.SkinnedMeshRenderer_StartAnimation(swigCPtr, SWIGTYPE_p_XnorCore__PointerT_XnorCore__Animation_t.getCPtr(animation));
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
  }

  public void StartBlending(SWIGTYPE_p_XnorCore__PointerT_XnorCore__Animation_t animation) {
    CoreCNative.SkinnedMeshRenderer_StartBlending(swigCPtr, SWIGTYPE_p_XnorCore__PointerT_XnorCore__Animation_t.getCPtr(animation));
    if (CoreCNative.SWIGPendingException.Pending) throw CoreCNative.SWIGPendingException.Retrieve();
  }

  public void SetCrossFadeDelta(float delta) {
    CoreCNative.SkinnedMeshRenderer_SetCrossFadeDelta(swigCPtr, delta);
  }

  public SWIGTYPE_p_XnorCore__ListT_Matrix_t GetMatrices() {
    SWIGTYPE_p_XnorCore__ListT_Matrix_t ret = new SWIGTYPE_p_XnorCore__ListT_Matrix_t(CoreCNative.SkinnedMeshRenderer_GetMatrices(swigCPtr), false);
    return ret;
  }

}

}
