//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class SpotLightData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SpotLightData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SpotLightData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SpotLightData obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SpotLightData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_SpotLightData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Vector3 color {
    set {
      CoreCNative.SpotLightData_color_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.SpotLightData_color_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

  public float intensity {
    set {
      CoreCNative.SpotLightData_intensity_set(swigCPtr, value);
    } 
    get {
      float ret = CoreCNative.SpotLightData_intensity_get(swigCPtr);
      return ret;
    } 
  }

  public Vector3 position {
    set {
      CoreCNative.SpotLightData_position_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.SpotLightData_position_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

  public float cutOff {
    set {
      CoreCNative.SpotLightData_cutOff_set(swigCPtr, value);
    } 
    get {
      float ret = CoreCNative.SpotLightData_cutOff_get(swigCPtr);
      return ret;
    } 
  }

  public Vector3 direction {
    set {
      CoreCNative.SpotLightData_direction_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.SpotLightData_direction_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

  public float outerCutOff {
    set {
      CoreCNative.SpotLightData_outerCutOff_set(swigCPtr, value);
    } 
    get {
      float ret = CoreCNative.SpotLightData_outerCutOff_get(swigCPtr);
      return ret;
    } 
  }

  public int isCastingShadow {
    set {
      CoreCNative.SpotLightData_isCastingShadow_set(swigCPtr, value);
    } 
    get {
      int ret = CoreCNative.SpotLightData_isCastingShadow_get(swigCPtr);
      return ret;
    } 
  }

  public SpotLightData() : this(CoreCNative.new_SpotLightData(), true) {
  }

}

}
