//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class StaticMeshRenderer : Component {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal StaticMeshRenderer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CoreCNative.StaticMeshRenderer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StaticMeshRenderer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(StaticMeshRenderer obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_StaticMeshRenderer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public SWIGTYPE_p_XnorCore__PointerT_XnorCore__Mesh_t mesh {
    set {
      CoreCNative.StaticMeshRenderer_mesh_set(swigCPtr, SWIGTYPE_p_XnorCore__PointerT_XnorCore__Mesh_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.StaticMeshRenderer_mesh_get(swigCPtr);
      SWIGTYPE_p_XnorCore__PointerT_XnorCore__Mesh_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_XnorCore__PointerT_XnorCore__Mesh_t(cPtr, false);
      return ret;
    } 
  }

  public Material material {
    set {
      CoreCNative.StaticMeshRenderer_material_set(swigCPtr, Material.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.StaticMeshRenderer_material_get(swigCPtr);
      Material ret = (cPtr == global::System.IntPtr.Zero) ? null : new Material(cPtr, false);
      return ret;
    } 
  }

  public bool drawModelAabb {
    set {
      CoreCNative.StaticMeshRenderer_drawModelAabb_set(swigCPtr, value);
    } 
    get {
      bool ret = CoreCNative.StaticMeshRenderer_drawModelAabb_get(swigCPtr);
      return ret;
    } 
  }

  public StaticMeshRenderer() : this(CoreCNative.new_StaticMeshRenderer(), true) {
  }

  public void GetAabb(Bound bound) {
    CoreCNative.StaticMeshRenderer_GetAabb(swigCPtr, Bound.getCPtr(bound));
  }

}

}
