//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public static class Time {
    public static float TotalTime => GetTotalTime();
    
    public static float LastTotalTime => GetLastTotalTime();
    
    public static float DeltaTime => GetDeltaTime();
    
    public static uint TotalFrameCount => GetTotalFrameCount();

  private static float GetTotalTime() {
    float ret = CoreCNative.Time_GetTotalTime();
    return ret;
  }

  private static float GetLastTotalTime() {
    float ret = CoreCNative.Time_GetLastTotalTime();
    return ret;
  }

  private static float GetDeltaTime() {
    float ret = CoreCNative.Time_GetDeltaTime();
    return ret;
  }

  private static uint GetTotalFrameCount() {
    uint ret = CoreCNative.Time_GetTotalFrameCount();
    return ret;
  }

}

}
