//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class VaoDescriptor : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VaoDescriptor(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VaoDescriptor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VaoDescriptor obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VaoDescriptor() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_VaoDescriptor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VertexAttributeBinding vertexAttributeBindings {
    set {
      CoreCNative.VaoDescriptor_vertexAttributeBindings_set(swigCPtr, VertexAttributeBinding.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.VaoDescriptor_vertexAttributeBindings_get(swigCPtr);
      VertexAttributeBinding ret = (cPtr == global::System.IntPtr.Zero) ? null : new VertexAttributeBinding(cPtr, false);
      return ret;
    } 
  }

  public uint vertexAttributeBindingSize {
    set {
      CoreCNative.VaoDescriptor_vertexAttributeBindingSize_set(swigCPtr, value);
    } 
    get {
      uint ret = CoreCNative.VaoDescriptor_vertexAttributeBindingSize_get(swigCPtr);
      return ret;
    } 
  }

  public VertexAttribFormat vertexAttribFormats {
    set {
      CoreCNative.VaoDescriptor_vertexAttribFormats_set(swigCPtr, VertexAttribFormat.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.VaoDescriptor_vertexAttribFormats_get(swigCPtr);
      VertexAttribFormat ret = (cPtr == global::System.IntPtr.Zero) ? null : new VertexAttribFormat(cPtr, false);
      return ret;
    } 
  }

  public uint vertexAttribFormatsSize {
    set {
      CoreCNative.VaoDescriptor_vertexAttribFormatsSize_set(swigCPtr, value);
    } 
    get {
      uint ret = CoreCNative.VaoDescriptor_vertexAttribFormatsSize_get(swigCPtr);
      return ret;
    } 
  }

  public uint vboId {
    set {
      CoreCNative.VaoDescriptor_vboId_set(swigCPtr, value);
    } 
    get {
      uint ret = CoreCNative.VaoDescriptor_vboId_get(swigCPtr);
      return ret;
    } 
  }

  public VaoDescriptor() : this(CoreCNative.new_VaoDescriptor(), true) {
  }

}

}
