//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class VBODescriptor : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VBODescriptor(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VBODescriptor obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VBODescriptor obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VBODescriptor() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_VBODescriptor(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VertexAttributePointer vertexAttributesPointer {
    set {
      CoreCNative.VBODescriptor_vertexAttributesPointer_set(swigCPtr, VertexAttributePointer.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.VBODescriptor_vertexAttributesPointer_get(swigCPtr);
      VertexAttributePointer ret = (cPtr == global::System.IntPtr.Zero) ? null : new VertexAttributePointer(cPtr, false);
      return ret;
    } 
  }

  public uint vboAttributePointerSize {
    set {
      CoreCNative.VBODescriptor_vboAttributePointerSize_set(swigCPtr, value);
    } 
    get {
      uint ret = CoreCNative.VBODescriptor_vboAttributePointerSize_get(swigCPtr);
      return ret;
    } 
  }

  public AttributeDivisor attributesDivisorPointer {
    set {
      CoreCNative.VBODescriptor_attributesDivisorPointer_set(swigCPtr, AttributeDivisor.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.VBODescriptor_attributesDivisorPointer_get(swigCPtr);
      AttributeDivisor ret = (cPtr == global::System.IntPtr.Zero) ? null : new AttributeDivisor(cPtr, false);
      return ret;
    } 
  }

  public uint attributesDivisorPointerSize {
    set {
      CoreCNative.VBODescriptor_attributesDivisorPointerSize_set(swigCPtr, value);
    } 
    get {
      uint ret = CoreCNative.VBODescriptor_attributesDivisorPointerSize_get(swigCPtr);
      return ret;
    } 
  }

  public VBODescriptor() : this(CoreCNative.new_VBODescriptor(), true) {
  }

}

}
