//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class VertexAttributePointer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VertexAttributePointer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VertexAttributePointer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VertexAttributePointer obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VertexAttributePointer() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_VertexAttributePointer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint index {
    set {
      CoreCNative.VertexAttributePointer_index_set(swigCPtr, value);
    } 
    get {
      uint ret = CoreCNative.VertexAttributePointer_index_get(swigCPtr);
      return ret;
    } 
  }

  public uint size {
    set {
      CoreCNative.VertexAttributePointer_size_set(swigCPtr, value);
    } 
    get {
      uint ret = CoreCNative.VertexAttributePointer_size_get(swigCPtr);
      return ret;
    } 
  }

  public DataType bufferDatatype {
    set {
      CoreCNative.VertexAttributePointer_bufferDatatype_set(swigCPtr, (int)value);
    } 
    get {
      DataType ret = (DataType)CoreCNative.VertexAttributePointer_bufferDatatype_get(swigCPtr);
      return ret;
    } 
  }

  public bool normalized {
    set {
      CoreCNative.VertexAttributePointer_normalized_set(swigCPtr, value);
    } 
    get {
      bool ret = CoreCNative.VertexAttributePointer_normalized_get(swigCPtr);
      return ret;
    } 
  }

  public uint stride {
    set {
      CoreCNative.VertexAttributePointer_stride_set(swigCPtr, value);
    } 
    get {
      uint ret = CoreCNative.VertexAttributePointer_stride_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pointer {
    set {
      CoreCNative.VertexAttributePointer_pointer_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.VertexAttributePointer_pointer_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public VertexAttributePointer() : this(CoreCNative.new_VertexAttributePointer(), true) {
  }

}

}
