//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor.Core {

public class Vertex : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vertex(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vertex obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Vertex obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Vertex() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoreCNative.delete_Vertex(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Vector3 position {
    set {
      CoreCNative.Vertex_position_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.Vertex_position_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

  public Vector3 normal {
    set {
      CoreCNative.Vertex_normal_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.Vertex_normal_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

  public Vector2 textureCoord {
    set {
      CoreCNative.Vertex_textureCoord_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.Vertex_textureCoord_get(swigCPtr);
			Vector2 ret = (Vector2) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector2));
			return ret;
		}
	
  }

  public Vector3 tangent {
    set {
      CoreCNative.Vertex_tangent_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.Vertex_tangent_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

  public Vector3 bitangent {
    set {
      CoreCNative.Vertex_bitangent_set(swigCPtr,  ref value );
    } 
		get { 
			nint ptr = CoreCNative.Vertex_bitangent_get(swigCPtr);
			Vector3 ret = (Vector3) global::System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(Vector3));
			return ret;
		}
	
  }

  public SWIGTYPE_p_float boneIndices {
    set {
      CoreCNative.Vertex_boneIndices_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.Vertex_boneIndices_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_float boneWeight {
    set {
      CoreCNative.Vertex_boneWeight_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CoreCNative.Vertex_boneWeight_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

  public Vertex() : this(CoreCNative.new_Vertex(), true) {
  }

  public static readonly uint MaxBoneWeight = CoreCNative.Vertex_MaxBoneWeight_get();
}

}
