//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor {

public enum BufferFlag {
  None = 0,
  ColorBit = 1 << 0,
  DepthBit = 1 << 1,
  StencilBit = 1 << 2
}

}
