//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor {

public class Camera : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Camera(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Camera obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Camera obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Camera() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CorePINVOKE.delete_Camera(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_Vector3 position {
    set {
      CorePINVOKE.Camera_position_set(swigCPtr, SWIGTYPE_p_Vector3.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Vector3 ret = new SWIGTYPE_p_Vector3(CorePINVOKE.Camera_position_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_Vector3 front {
    set {
      CorePINVOKE.Camera_front_set(swigCPtr, SWIGTYPE_p_Vector3.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Vector3 ret = new SWIGTYPE_p_Vector3(CorePINVOKE.Camera_front_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_Vector3 up {
    set {
      CorePINVOKE.Camera_up_set(swigCPtr, SWIGTYPE_p_Vector3.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Vector3 ret = new SWIGTYPE_p_Vector3(CorePINVOKE.Camera_up_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_Vector3 right {
    set {
      CorePINVOKE.Camera_right_set(swigCPtr, SWIGTYPE_p_Vector3.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Vector3 ret = new SWIGTYPE_p_Vector3(CorePINVOKE.Camera_right_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_float_t near {
    set {
      CorePINVOKE.Camera_near_set(swigCPtr, SWIGTYPE_p_float_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_float_t ret = new SWIGTYPE_p_float_t(CorePINVOKE.Camera_near_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_float_t far {
    set {
      CorePINVOKE.Camera_far_set(swigCPtr, SWIGTYPE_p_float_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_float_t ret = new SWIGTYPE_p_float_t(CorePINVOKE.Camera_far_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_float_t fov {
    set {
      CorePINVOKE.Camera_fov_set(swigCPtr, SWIGTYPE_p_float_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_float_t ret = new SWIGTYPE_p_float_t(CorePINVOKE.Camera_fov_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public void GetProjection(SWIGTYPE_p_Vector2i screenSize, SWIGTYPE_p_Matrix matrix) {
    CorePINVOKE.Camera_GetProjection(swigCPtr, SWIGTYPE_p_Vector2i.getCPtr(screenSize), SWIGTYPE_p_Matrix.getCPtr(matrix));
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetView(SWIGTYPE_p_Matrix matrix) {
    CorePINVOKE.Camera_GetView(swigCPtr, SWIGTYPE_p_Matrix.getCPtr(matrix));
  }

  public void GetVp(SWIGTYPE_p_Vector2i screenSize, SWIGTYPE_p_Matrix matrix) {
    CorePINVOKE.Camera_GetVp(swigCPtr, SWIGTYPE_p_Vector2i.getCPtr(screenSize), SWIGTYPE_p_Matrix.getCPtr(matrix));
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  public void LookAt(SWIGTYPE_p_Vector3 at) {
    CorePINVOKE.Camera_LookAt(swigCPtr, SWIGTYPE_p_Vector3.getCPtr(at));
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_Vector2i ProjectOn(SWIGTYPE_p_Vector3 vertex, SWIGTYPE_p_Vector2i screenSize, SWIGTYPE_p_Matrix model) {
    SWIGTYPE_p_Vector2i ret = new SWIGTYPE_p_Vector2i(CorePINVOKE.Camera_ProjectOn(swigCPtr, SWIGTYPE_p_Vector3.getCPtr(vertex), SWIGTYPE_p_Vector2i.getCPtr(screenSize), SWIGTYPE_p_Matrix.getCPtr(model)), true);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Camera() : this(CorePINVOKE.new_Camera(), true) {
  }

}

}
