//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor {

public class ColorRgba : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ColorRgba(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ColorRgba obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ColorRgba obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ColorRgba() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CorePINVOKE.delete_ColorRgba(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_uint8_t r {
    set {
      CorePINVOKE.ColorRgba_r_set(swigCPtr, SWIGTYPE_p_uint8_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint8_t ret = new SWIGTYPE_p_uint8_t(CorePINVOKE.ColorRgba_r_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint8_t g {
    set {
      CorePINVOKE.ColorRgba_g_set(swigCPtr, SWIGTYPE_p_uint8_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint8_t ret = new SWIGTYPE_p_uint8_t(CorePINVOKE.ColorRgba_g_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint8_t b {
    set {
      CorePINVOKE.ColorRgba_b_set(swigCPtr, SWIGTYPE_p_uint8_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint8_t ret = new SWIGTYPE_p_uint8_t(CorePINVOKE.ColorRgba_b_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint8_t a {
    set {
      CorePINVOKE.ColorRgba_a_set(swigCPtr, SWIGTYPE_p_uint8_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint8_t ret = new SWIGTYPE_p_uint8_t(CorePINVOKE.ColorRgba_a_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ColorRgba() : this(CorePINVOKE.new_ColorRgba__SWIG_0(), true) {
  }

  public ColorRgba(SWIGTYPE_p_uint32_t rgba) : this(CorePINVOKE.new_ColorRgba__SWIG_1(SWIGTYPE_p_uint32_t.getCPtr(rgba)), true) {
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  public ColorRgba(SWIGTYPE_p_uint8_t r, SWIGTYPE_p_uint8_t g, SWIGTYPE_p_uint8_t b, SWIGTYPE_p_uint8_t a) : this(CorePINVOKE.new_ColorRgba__SWIG_2(SWIGTYPE_p_uint8_t.getCPtr(r), SWIGTYPE_p_uint8_t.getCPtr(g), SWIGTYPE_p_uint8_t.getCPtr(b), SWIGTYPE_p_uint8_t.getCPtr(a)), true) {
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  public ColorRgba(SWIGTYPE_p_uint8_t r, SWIGTYPE_p_uint8_t g, SWIGTYPE_p_uint8_t b) : this(CorePINVOKE.new_ColorRgba__SWIG_3(SWIGTYPE_p_uint8_t.getCPtr(r), SWIGTYPE_p_uint8_t.getCPtr(g), SWIGTYPE_p_uint8_t.getCPtr(b)), true) {
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
