//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor {

public class Directory : Entry {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Directory(global::System.IntPtr cPtr, bool cMemoryOwn) : base(CorePINVOKE.Directory_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Directory obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Directory obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CorePINVOKE.delete_Directory(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Directory(SWIGTYPE_p_std__filesystem__path filepath) : this(CorePINVOKE.new_Directory(SWIGTYPE_p_std__filesystem__path.swigRelease(filepath)), true) {
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool Load() {
    bool ret = CorePINVOKE.Directory_Load(swigCPtr);
    return ret;
  }

  public override void Unload() {
    CorePINVOKE.Directory_Unload(swigCPtr);
  }

  public override void OpenInExplorer() {
    CorePINVOKE.Directory_OpenInExplorer(swigCPtr);
  }

  public SWIGTYPE_p_std__vectorT_XnorCore__PointerT_XnorCore__Entry_t_t GetChildEntries() {
    SWIGTYPE_p_std__vectorT_XnorCore__PointerT_XnorCore__Entry_t_t ret = new SWIGTYPE_p_std__vectorT_XnorCore__PointerT_XnorCore__Entry_t_t(CorePINVOKE.Directory_GetChildEntries__SWIG_0(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_XnorCore__PointerT_XnorCore__File_t_t GetChildFiles() {
    SWIGTYPE_p_std__vectorT_XnorCore__PointerT_XnorCore__File_t_t ret = new SWIGTYPE_p_std__vectorT_XnorCore__PointerT_XnorCore__File_t_t(CorePINVOKE.Directory_GetChildFiles__SWIG_0(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_XnorCore__PointerT_XnorCore__Directory_t_t GetChildDirectories() {
    SWIGTYPE_p_std__vectorT_XnorCore__PointerT_XnorCore__Directory_t_t ret = new SWIGTYPE_p_std__vectorT_XnorCore__PointerT_XnorCore__Directory_t_t(CorePINVOKE.Directory_GetChildDirectories__SWIG_0(swigCPtr), false);
    return ret;
  }

  public override void SetName(string newName) {
    CorePINVOKE.Directory_SetName(swigCPtr, newName);
    if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
