//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor {

public class GpuLightData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GpuLightData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GpuLightData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(GpuLightData obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~GpuLightData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CorePINVOKE.delete_GpuLightData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_uint32_t nbrOfPointLight {
    set {
      CorePINVOKE.GpuLightData_nbrOfPointLight_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(CorePINVOKE.GpuLightData_nbrOfPointLight_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t nbrOfSpotLight {
    set {
      CorePINVOKE.GpuLightData_nbrOfSpotLight_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(CorePINVOKE.GpuLightData_nbrOfSpotLight_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t padding1 {
    set {
      CorePINVOKE.GpuLightData_padding1_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(CorePINVOKE.GpuLightData_padding1_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint32_t padding2 {
    set {
      CorePINVOKE.GpuLightData_padding2_set(swigCPtr, SWIGTYPE_p_uint32_t.getCPtr(value));
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint32_t ret = new SWIGTYPE_p_uint32_t(CorePINVOKE.GpuLightData_padding2_get(swigCPtr), true);
      if (CorePINVOKE.SWIGPendingException.Pending) throw CorePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public PointLightData pointLightData {
    set {
      CorePINVOKE.GpuLightData_pointLightData_set(swigCPtr, PointLightData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CorePINVOKE.GpuLightData_pointLightData_get(swigCPtr);
      PointLightData ret = (cPtr == global::System.IntPtr.Zero) ? null : new PointLightData(cPtr, false);
      return ret;
    } 
  }

  public SpotLightData spotLightData {
    set {
      CorePINVOKE.GpuLightData_spotLightData_set(swigCPtr, SpotLightData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CorePINVOKE.GpuLightData_spotLightData_get(swigCPtr);
      SpotLightData ret = (cPtr == global::System.IntPtr.Zero) ? null : new SpotLightData(cPtr, false);
      return ret;
    } 
  }

  public DirectionalLightData directionalData {
    set {
      CorePINVOKE.GpuLightData_directionalData_set(swigCPtr, DirectionalLightData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CorePINVOKE.GpuLightData_directionalData_get(swigCPtr);
      DirectionalLightData ret = (cPtr == global::System.IntPtr.Zero) ? null : new DirectionalLightData(cPtr, false);
      return ret;
    } 
  }

  public GpuLightData() : this(CorePINVOKE.new_GpuLightData(), true) {
  }

}

}
