//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor {

public class Material : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Material(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Material obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Material obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Material() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CorePINVOKE.delete_Material(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public MaterialType materialType {
    set {
      CorePINVOKE.Material_materialType_set(swigCPtr, (int)value);
    } 
    get {
      MaterialType ret = (MaterialType)CorePINVOKE.Material_materialType_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_XnorCore__PointerT_XnorCore__Texture_t albedo {
    set {
      CorePINVOKE.Material_albedo_set(swigCPtr, SWIGTYPE_p_XnorCore__PointerT_XnorCore__Texture_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CorePINVOKE.Material_albedo_get(swigCPtr);
      SWIGTYPE_p_XnorCore__PointerT_XnorCore__Texture_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_XnorCore__PointerT_XnorCore__Texture_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_XnorCore__PointerT_XnorCore__Texture_t normalMap {
    set {
      CorePINVOKE.Material_normalMap_set(swigCPtr, SWIGTYPE_p_XnorCore__PointerT_XnorCore__Texture_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CorePINVOKE.Material_normalMap_get(swigCPtr);
      SWIGTYPE_p_XnorCore__PointerT_XnorCore__Texture_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_XnorCore__PointerT_XnorCore__Texture_t(cPtr, false);
      return ret;
    } 
  }

  public Material() : this(CorePINVOKE.new_Material(), true) {
  }

}

}
