//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor {

public enum TextureType {
  Texture1D,
  Texture2D,
  Texture3D,
  Texture1DArray,
  Texture2DArray,
  TextureRectangle,
  TextureCubeMap,
  TextureCubeMapArray,
  TextureBuffer,
  Texture2DMultisample,
  Texture2DMultisampleArray
}

}
