//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Xnor {

public class World : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal World(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(World obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(World obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~World() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static void Begin() {
    CorePINVOKE.World_Begin();
  }

  public static void Update() {
    CorePINVOKE.World_Update();
  }

  public static bool isPlaying {
    set {
      CorePINVOKE.World_isPlaying_set(value);
    } 
    get {
      bool ret = CorePINVOKE.World_isPlaying_get();
      return ret;
    } 
  }

  public static bool hasStarted {
    set {
      CorePINVOKE.World_hasStarted_set(value);
    } 
    get {
      bool ret = CorePINVOKE.World_hasStarted_get();
      return ret;
    } 
  }

  public static Scene scene {
    set {
      CorePINVOKE.World_scene_set(Scene.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CorePINVOKE.World_scene_get();
      Scene ret = (cPtr == global::System.IntPtr.Zero) ? null : new Scene(cPtr, false);
      return ret;
    } 
  }

}

}
